<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>activemq-cpp-3.3.0: cms::XAException Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript">
$(document).ready(initResizable);
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.7.3 -->
<div id="top">
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td style="padding-left: 0.5em;">
   <div id="projectname">activemq-cpp-3.3.0</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Data&#160;Structures</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.html"><span>Data&#160;Structures</span></a></li>
      <li><a href="hierarchy.html"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Data&#160;Fields</span></a></li>
    </ul>
  </div>
</div>
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
  initNavTree('classcms_1_1_x_a_exception.html','');
</script>
<div id="doc-content">
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a>  </div>
  <div class="headertitle">
<h1>cms::XAException Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="cms::XAException" --><!-- doxytag: inherits="cms::CMSException" -->
<p>The <a class="el" href="classcms_1_1_x_a_exception.html" title="The XAException is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error ...">XAException</a> is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error encountered by the involved transaction.  
<a href="#_details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_x_a_exception_8h_source.html">src/main/cms/XAException.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for cms::XAException:</div>
<div class="dyncontent">
<div class="center"><img src="classcms_1_1_x_a_exception__inherit__graph.png" border="0" usemap="#cms_1_1_x_a_exception_inherit__map" alt="Inheritance graph"/></div>
<map name="cms_1_1_x_a_exception_inherit__map" id="cms_1_1_x_a_exception_inherit__map">
<area shape="rect" id="node2" href="classcms_1_1_c_m_s_exception.html" title="CMS API Exception that is the base for all exceptions thrown from CMS classes." alt="" coords="5,5,163,35"/></map>
<center><span class="legend">[<a target="top" href="graph_legend.html">legend</a>]</span></center></div>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a59c6ea0aae2421e1365e1e36d9947250">XAException</a> ()</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a2c37e6ca61719c20200969216caa909b">XAException</a> (int errorCode)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a90e7fd50af7b3b87d12276a3e7a482d6">XAException</a> (const <a class="el" href="classcms_1_1_x_a_exception.html">XAException</a> &amp;ex)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a9fb2185d20190f91d61a6e3c9a65232d">XAException</a> (const std::string &amp;message)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#abf7b3841a5ceb8b12718f3d215f26b37">XAException</a> (const std::string &amp;message, const std::exception *cause)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#aa2a42a655e3769ba4ce58297ea26d916">XAException</a> (const std::string &amp;message, const std::exception *cause, const std::vector&lt; std::pair&lt; std::string, int &gt; &gt; &amp;stackTrace)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a376b5d2100256f29e350d034b81f80bd">~XAException</a> ()  throw ()</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a44622e836c61572896b78dc6fb731234">setErrorCode</a> (int errorCode)</td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Sets the error code for this <a class="el" href="classcms_1_1_x_a_exception.html" title="The XAException is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error ...">XAException</a>.  <a href="#a44622e836c61572896b78dc6fb731234"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#afe8c4d9b3680349cacd08b919518dcad">getErrorCode</a> () const </td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Gets the error code that was assigned to this <a class="el" href="classcms_1_1_x_a_exception.html" title="The XAException is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error ...">XAException</a>.  <a href="#afe8c4d9b3680349cacd08b919518dcad"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a17eed4799c0896db50f01a7748877412">XA_RBBASE</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which contains the inclusive lower bound of the rollback error codes.  <a href="#a17eed4799c0896db50f01a7748877412"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a78ec1c4fca015b211ddd91ce147631d7">XA_RBROLLBACK</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the rollback occurred for an unspecified reason.  <a href="#a78ec1c4fca015b211ddd91ce147631d7"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#ac4722cfa9cda8ab98df416f1ab5fb1f5">XA_RBCOMMFAIL</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that rollback was caused by a communication failure.  <a href="#ac4722cfa9cda8ab98df416f1ab5fb1f5"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#ad22e000dee6ac2c6c30122c0a960aacb">XA_RBDEADLOCK</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that a failure occurred because a deadlock was detected.  <a href="#ad22e000dee6ac2c6c30122c0a960aacb"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#ab30a2e83a0a03fbbfdf21fe67ce8b460">XA_RBINTEGRITY</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that a condition was detected than implies a violation of the integrity of the resource.  <a href="#ab30a2e83a0a03fbbfdf21fe67ce8b460"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a88d0b0ca8fbbcf594fc347b75656c3ff">XA_RBOTHER</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the Resource Manager rolled back the transaction branch for a reason not separately listed.  <a href="#a88d0b0ca8fbbcf594fc347b75656c3ff"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a4a9ae5c8bfb80b7b1946991b3b8b14b8">XA_RBPROTO</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that a protocol error occurred in the Resource Manager.  <a href="#a4a9ae5c8bfb80b7b1946991b3b8b14b8"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a5e348f99c7662abfcba4a4f20d6f1643">XA_RBTIMEOUT</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that a transaction branch took too long.  <a href="#a5e348f99c7662abfcba4a4f20d6f1643"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a7e66243f95becf2e6c6b30ae0be41e0c">XA_RBTRANSIENT</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the caller may retry the transaction branch.  <a href="#a7e66243f95becf2e6c6b30ae0be41e0c"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#ab3b095c49af1483896c48f27b1ebec6e">XA_RBEND</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which contains the inclusive upper bound of the rollback error codes.  <a href="#ab3b095c49af1483896c48f27b1ebec6e"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a6af7ed07f35c3b7080306b2bc1521d0c">XA_NOMIGRATE</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that resumption must occur where the suspension occurred.  <a href="#a6af7ed07f35c3b7080306b2bc1521d0c"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a5c88176085f7566eee9ac2b81bae71e0">XA_HEURHAZ</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the transaction branch may have been heuristically completed.  <a href="#a5c88176085f7566eee9ac2b81bae71e0"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a4c0765a37250a44738e7803101c50b2c">XA_HEURCOM</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the transaction branch has been heuristically committed.  <a href="#a4c0765a37250a44738e7803101c50b2c"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a7b028908b8adcb13f605e097c5e88628">XA_HEURRB</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the transaction branch has been heuristically rolled back.  <a href="#a7b028908b8adcb13f605e097c5e88628"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a8d665cd105afe737837a548b1da906b4">XA_HEURMIX</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the transaction branch has been heuristically committed and rolled back.  <a href="#a8d665cd105afe737837a548b1da906b4"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#adba1a72c26e46ed16662b233b5775d01">XA_RETRY</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the method returned with no effect and can be reissued.  <a href="#adba1a72c26e46ed16662b233b5775d01"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#ae76eb7e9c29fd2e5a9ebdb69e26fa5e9">XA_RDONLY</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the transaction branch was read only and has been committed.  <a href="#ae76eb7e9c29fd2e5a9ebdb69e26fa5e9"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a4a7d6543ddf34aed98a7e3f5ebbbb122">XAER_ASYNC</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that there is already an asynchronous operation outstanding.  <a href="#a4a7d6543ddf34aed98a7e3f5ebbbb122"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a084b5affe91c8c4d20f0ee15a28b3c6b">XAER_RMERR</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that a Resource Manager error has occurred for the transaction branch.  <a href="#a084b5affe91c8c4d20f0ee15a28b3c6b"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#abe7e87ec67e525882bef4d7ad4d0cce4">XAER_NOTA</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the XID is not valid.  <a href="#abe7e87ec67e525882bef4d7ad4d0cce4"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#aba4bcc93735a487239ef1df4e217131c">XAER_INVAL</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that invalid arguments were supplied.  <a href="#aba4bcc93735a487239ef1df4e217131c"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#aa9510354356a716a27a38cc4ecb403ed">XAER_PROTO</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the method was invoked in an improper context.  <a href="#aa9510354356a716a27a38cc4ecb403ed"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a27eeaee0c0c50c3027b9e9fa2c8e22ba">XAER_RMFAIL</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the Resource Manager is unavailable.  <a href="#a27eeaee0c0c50c3027b9e9fa2c8e22ba"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a3271e558ea9e397db558068aeb337fca">XAER_DUPID</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Code which means that the XID already exists.  <a href="#a3271e558ea9e397db558068aeb337fca"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static const int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcms_1_1_x_a_exception.html#a062bc5a05012729b4b8112d4ead3c9a3">XAER_OUTSIDE</a></td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Work is being done by the Resource Manager outside the boundaries of a global transaction.  <a href="#a062bc5a05012729b4b8112d4ead3c9a3"></a><br/></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<div class="textblock"><p>The <a class="el" href="classcms_1_1_x_a_exception.html" title="The XAException is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error ...">XAException</a> is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error encountered by the involved transaction. </p>
<dl class="since"><dt><b>Since:</b></dt><dd>2.3 </dd></dl>
</div><hr/><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a59c6ea0aae2421e1365e1e36d9947250"></a><!-- doxytag: member="cms::XAException::XAException" ref="a59c6ea0aae2421e1365e1e36d9947250" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cms::XAException::XAException </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="a2c37e6ca61719c20200969216caa909b"></a><!-- doxytag: member="cms::XAException::XAException" ref="a2c37e6ca61719c20200969216caa909b" args="(int errorCode)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cms::XAException::XAException </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>errorCode</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="a90e7fd50af7b3b87d12276a3e7a482d6"></a><!-- doxytag: member="cms::XAException::XAException" ref="a90e7fd50af7b3b87d12276a3e7a482d6" args="(const XAException &amp;ex)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cms::XAException::XAException </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classcms_1_1_x_a_exception.html">XAException</a> &amp;&#160;</td>
          <td class="paramname"><em>ex</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="a9fb2185d20190f91d61a6e3c9a65232d"></a><!-- doxytag: member="cms::XAException::XAException" ref="a9fb2185d20190f91d61a6e3c9a65232d" args="(const std::string &amp;message)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cms::XAException::XAException </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>message</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="abf7b3841a5ceb8b12718f3d215f26b37"></a><!-- doxytag: member="cms::XAException::XAException" ref="abf7b3841a5ceb8b12718f3d215f26b37" args="(const std::string &amp;message, const std::exception *cause)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cms::XAException::XAException </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>message</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::exception *&#160;</td>
          <td class="paramname"><em>cause</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="aa2a42a655e3769ba4ce58297ea26d916"></a><!-- doxytag: member="cms::XAException::XAException" ref="aa2a42a655e3769ba4ce58297ea26d916" args="(const std::string &amp;message, const std::exception *cause, const std::vector&lt; std::pair&lt; std::string, int &gt; &gt; &amp;stackTrace)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cms::XAException::XAException </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>message</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::exception *&#160;</td>
          <td class="paramname"><em>cause</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; std::pair&lt; std::string, int &gt; &gt; &amp;&#160;</td>
          <td class="paramname"><em>stackTrace</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="a376b5d2100256f29e350d034b81f80bd"></a><!-- doxytag: member="cms::XAException::~XAException" ref="a376b5d2100256f29e350d034b81f80bd" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual cms::XAException::~XAException </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td>  throw ()<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="afe8c4d9b3680349cacd08b919518dcad"></a><!-- doxytag: member="cms::XAException::getErrorCode" ref="afe8c4d9b3680349cacd08b919518dcad" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">int cms::XAException::getErrorCode </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const<code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets the error code that was assigned to this <a class="el" href="classcms_1_1_x_a_exception.html" title="The XAException is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error ...">XAException</a>. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>the assigned error code. </dd></dl>

</div>
</div>
<a class="anchor" id="a44622e836c61572896b78dc6fb731234"></a><!-- doxytag: member="cms::XAException::setErrorCode" ref="a44622e836c61572896b78dc6fb731234" args="(int errorCode)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void cms::XAException::setErrorCode </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>errorCode</em></td><td>)</td>
          <td><code> [inline]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Sets the error code for this <a class="el" href="classcms_1_1_x_a_exception.html" title="The XAException is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error ...">XAException</a>. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table class="params">
    <tr><td class="paramname">errorCode</td><td>The error code to assign to this <a class="el" href="classcms_1_1_x_a_exception.html" title="The XAException is thrown by the Resource Manager (RM) to inform the Transaction Manager of an error ...">XAException</a>. </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/><h2>Field Documentation</h2>
<a class="anchor" id="a4c0765a37250a44738e7803101c50b2c"></a><!-- doxytag: member="cms::XAException::XA_HEURCOM" ref="a4c0765a37250a44738e7803101c50b2c" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a4c0765a37250a44738e7803101c50b2c">cms::XAException::XA_HEURCOM</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the transaction branch has been heuristically committed. </p>

</div>
</div>
<a class="anchor" id="a5c88176085f7566eee9ac2b81bae71e0"></a><!-- doxytag: member="cms::XAException::XA_HEURHAZ" ref="a5c88176085f7566eee9ac2b81bae71e0" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a5c88176085f7566eee9ac2b81bae71e0">cms::XAException::XA_HEURHAZ</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the transaction branch may have been heuristically completed. </p>

</div>
</div>
<a class="anchor" id="a8d665cd105afe737837a548b1da906b4"></a><!-- doxytag: member="cms::XAException::XA_HEURMIX" ref="a8d665cd105afe737837a548b1da906b4" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a8d665cd105afe737837a548b1da906b4">cms::XAException::XA_HEURMIX</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the transaction branch has been heuristically committed and rolled back. </p>

</div>
</div>
<a class="anchor" id="a7b028908b8adcb13f605e097c5e88628"></a><!-- doxytag: member="cms::XAException::XA_HEURRB" ref="a7b028908b8adcb13f605e097c5e88628" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a7b028908b8adcb13f605e097c5e88628">cms::XAException::XA_HEURRB</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the transaction branch has been heuristically rolled back. </p>

</div>
</div>
<a class="anchor" id="a6af7ed07f35c3b7080306b2bc1521d0c"></a><!-- doxytag: member="cms::XAException::XA_NOMIGRATE" ref="a6af7ed07f35c3b7080306b2bc1521d0c" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a6af7ed07f35c3b7080306b2bc1521d0c">cms::XAException::XA_NOMIGRATE</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that resumption must occur where the suspension occurred. </p>

</div>
</div>
<a class="anchor" id="a17eed4799c0896db50f01a7748877412"></a><!-- doxytag: member="cms::XAException::XA_RBBASE" ref="a17eed4799c0896db50f01a7748877412" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a17eed4799c0896db50f01a7748877412">cms::XAException::XA_RBBASE</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which contains the inclusive lower bound of the rollback error codes. </p>

</div>
</div>
<a class="anchor" id="ac4722cfa9cda8ab98df416f1ab5fb1f5"></a><!-- doxytag: member="cms::XAException::XA_RBCOMMFAIL" ref="ac4722cfa9cda8ab98df416f1ab5fb1f5" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#ac4722cfa9cda8ab98df416f1ab5fb1f5">cms::XAException::XA_RBCOMMFAIL</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that rollback was caused by a communication failure. </p>

</div>
</div>
<a class="anchor" id="ad22e000dee6ac2c6c30122c0a960aacb"></a><!-- doxytag: member="cms::XAException::XA_RBDEADLOCK" ref="ad22e000dee6ac2c6c30122c0a960aacb" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#ad22e000dee6ac2c6c30122c0a960aacb">cms::XAException::XA_RBDEADLOCK</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that a failure occurred because a deadlock was detected. </p>

</div>
</div>
<a class="anchor" id="ab3b095c49af1483896c48f27b1ebec6e"></a><!-- doxytag: member="cms::XAException::XA_RBEND" ref="ab3b095c49af1483896c48f27b1ebec6e" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#ab3b095c49af1483896c48f27b1ebec6e">cms::XAException::XA_RBEND</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which contains the inclusive upper bound of the rollback error codes. </p>

</div>
</div>
<a class="anchor" id="ab30a2e83a0a03fbbfdf21fe67ce8b460"></a><!-- doxytag: member="cms::XAException::XA_RBINTEGRITY" ref="ab30a2e83a0a03fbbfdf21fe67ce8b460" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#ab30a2e83a0a03fbbfdf21fe67ce8b460">cms::XAException::XA_RBINTEGRITY</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that a condition was detected than implies a violation of the integrity of the resource. </p>

</div>
</div>
<a class="anchor" id="a88d0b0ca8fbbcf594fc347b75656c3ff"></a><!-- doxytag: member="cms::XAException::XA_RBOTHER" ref="a88d0b0ca8fbbcf594fc347b75656c3ff" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a88d0b0ca8fbbcf594fc347b75656c3ff">cms::XAException::XA_RBOTHER</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the Resource Manager rolled back the transaction branch for a reason not separately listed. </p>

</div>
</div>
<a class="anchor" id="a4a9ae5c8bfb80b7b1946991b3b8b14b8"></a><!-- doxytag: member="cms::XAException::XA_RBPROTO" ref="a4a9ae5c8bfb80b7b1946991b3b8b14b8" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a4a9ae5c8bfb80b7b1946991b3b8b14b8">cms::XAException::XA_RBPROTO</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that a protocol error occurred in the Resource Manager. </p>

</div>
</div>
<a class="anchor" id="a78ec1c4fca015b211ddd91ce147631d7"></a><!-- doxytag: member="cms::XAException::XA_RBROLLBACK" ref="a78ec1c4fca015b211ddd91ce147631d7" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a78ec1c4fca015b211ddd91ce147631d7">cms::XAException::XA_RBROLLBACK</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the rollback occurred for an unspecified reason. </p>

</div>
</div>
<a class="anchor" id="a5e348f99c7662abfcba4a4f20d6f1643"></a><!-- doxytag: member="cms::XAException::XA_RBTIMEOUT" ref="a5e348f99c7662abfcba4a4f20d6f1643" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a5e348f99c7662abfcba4a4f20d6f1643">cms::XAException::XA_RBTIMEOUT</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that a transaction branch took too long. </p>

</div>
</div>
<a class="anchor" id="a7e66243f95becf2e6c6b30ae0be41e0c"></a><!-- doxytag: member="cms::XAException::XA_RBTRANSIENT" ref="a7e66243f95becf2e6c6b30ae0be41e0c" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a7e66243f95becf2e6c6b30ae0be41e0c">cms::XAException::XA_RBTRANSIENT</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the caller may retry the transaction branch. </p>

</div>
</div>
<a class="anchor" id="ae76eb7e9c29fd2e5a9ebdb69e26fa5e9"></a><!-- doxytag: member="cms::XAException::XA_RDONLY" ref="ae76eb7e9c29fd2e5a9ebdb69e26fa5e9" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#ae76eb7e9c29fd2e5a9ebdb69e26fa5e9">cms::XAException::XA_RDONLY</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the transaction branch was read only and has been committed. </p>

</div>
</div>
<a class="anchor" id="adba1a72c26e46ed16662b233b5775d01"></a><!-- doxytag: member="cms::XAException::XA_RETRY" ref="adba1a72c26e46ed16662b233b5775d01" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#adba1a72c26e46ed16662b233b5775d01">cms::XAException::XA_RETRY</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the method returned with no effect and can be reissued. </p>

</div>
</div>
<a class="anchor" id="a4a7d6543ddf34aed98a7e3f5ebbbb122"></a><!-- doxytag: member="cms::XAException::XAER_ASYNC" ref="a4a7d6543ddf34aed98a7e3f5ebbbb122" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a4a7d6543ddf34aed98a7e3f5ebbbb122">cms::XAException::XAER_ASYNC</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that there is already an asynchronous operation outstanding. </p>

</div>
</div>
<a class="anchor" id="a3271e558ea9e397db558068aeb337fca"></a><!-- doxytag: member="cms::XAException::XAER_DUPID" ref="a3271e558ea9e397db558068aeb337fca" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a3271e558ea9e397db558068aeb337fca">cms::XAException::XAER_DUPID</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the XID already exists. </p>

</div>
</div>
<a class="anchor" id="aba4bcc93735a487239ef1df4e217131c"></a><!-- doxytag: member="cms::XAException::XAER_INVAL" ref="aba4bcc93735a487239ef1df4e217131c" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#aba4bcc93735a487239ef1df4e217131c">cms::XAException::XAER_INVAL</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that invalid arguments were supplied. </p>

</div>
</div>
<a class="anchor" id="abe7e87ec67e525882bef4d7ad4d0cce4"></a><!-- doxytag: member="cms::XAException::XAER_NOTA" ref="abe7e87ec67e525882bef4d7ad4d0cce4" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#abe7e87ec67e525882bef4d7ad4d0cce4">cms::XAException::XAER_NOTA</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the XID is not valid. </p>

</div>
</div>
<a class="anchor" id="a062bc5a05012729b4b8112d4ead3c9a3"></a><!-- doxytag: member="cms::XAException::XAER_OUTSIDE" ref="a062bc5a05012729b4b8112d4ead3c9a3" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a062bc5a05012729b4b8112d4ead3c9a3">cms::XAException::XAER_OUTSIDE</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Work is being done by the Resource Manager outside the boundaries of a global transaction. </p>

</div>
</div>
<a class="anchor" id="aa9510354356a716a27a38cc4ecb403ed"></a><!-- doxytag: member="cms::XAException::XAER_PROTO" ref="aa9510354356a716a27a38cc4ecb403ed" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#aa9510354356a716a27a38cc4ecb403ed">cms::XAException::XAER_PROTO</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the method was invoked in an improper context. </p>

</div>
</div>
<a class="anchor" id="a084b5affe91c8c4d20f0ee15a28b3c6b"></a><!-- doxytag: member="cms::XAException::XAER_RMERR" ref="a084b5affe91c8c4d20f0ee15a28b3c6b" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a084b5affe91c8c4d20f0ee15a28b3c6b">cms::XAException::XAER_RMERR</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that a Resource Manager error has occurred for the transaction branch. </p>

</div>
</div>
<a class="anchor" id="a27eeaee0c0c50c3027b9e9fa2c8e22ba"></a><!-- doxytag: member="cms::XAException::XAER_RMFAIL" ref="a27eeaee0c0c50c3027b9e9fa2c8e22ba" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const int <a class="el" href="classcms_1_1_x_a_exception.html#a27eeaee0c0c50c3027b9e9fa2c8e22ba">cms::XAException::XAER_RMFAIL</a><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Code which means that the Resource Manager is unavailable. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>src/main/cms/<a class="el" href="_x_a_exception_8h_source.html">XAException.h</a></li>
</ul>
</div>
</div>
  <div id="nav-path" class="navpath">
    <ul>
      <li class="navelem"><a class="el" href="namespacecms.html">cms</a>      </li>
      <li class="navelem"><a class="el" href="classcms_1_1_x_a_exception.html">XAException</a>      </li>
      <li class="footer">Generated on Tue Apr 12 2011 for activemq-cpp-3.3.0 by&#160;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.7.3 </li>
    </ul>
  </div>

</body>
</html>
